#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue May 14 12:04:48 2019

@author: lovelace
"""

import pandas as pd                                                             
import matplotlib.pyplot as plt
JOINT=pd.read_csv("JUNTOS.csv")
df=pd.read_csv("JUNTOS.csv")


#------------------------------------------------------------------------------
"""
fig = plt.figure(figsize=(20,5))
plt.grid(True, linewidth=0, linestyle="dotted", color = "0.7")
plt.title("SPOT VS FUTURO", weight="bold", size=15, color = "0.3")
plt.xlabel('Fechas en el año 2019', weight="bold", size=12)
plt.plot(JOINT['Date'], df['SPOT'], color = 'blue')
plt.plot(JOINT['Date'], df['FUTURO'], color = 'green')
plt.savefig("Superpuesta.png")
"""
#------------------------------------------------------------------------------

from tkinter import *
import tkinter
import tkinter.messagebox
from PIL import Image
import math

def tasa(l,e):
  v=((l/100)-(e/100))
  return v

def valor(r,t):
  w=math.exp((r/100)*(t/360))
  return w

def precio(s,l,e,t):
  z=s*valor(tasa(l,e),t)
  return z

def ejecutar(s,l,e,t,y):
  x=precio(s,l,e,t)
  f=s*valor(l,t)
  p=f/y
  i=1*valor(e,t)
  i2=s*valor(l,t)
  g=p-i
  z=y*i
  g2=z-i2
  if (y<x):
    print("La estrategia de arbitraje es la siguiente:\n En t=0 días.\n 1. Suscribir un contrato futuro en {0} para {1} días. \n 2. Pedir prestado 1 dólar al mismo plazo con interés de {2} %. \n 3. Cambiar el dólar prestado por ${3}  en el mercado de contado. \n 4. Invertir los ${4} a una tasa de {5} %  al mismo plazo. \n \n En t= {6} días.\n 1. Recibir inversión de ${7} . \n 2. Cambiar a ${8} dólares  usando el derivado.\n 3. Pagar el préstamo inicial por ${9} dólares.\ 4. La ganancia es {10} dólares.".format(y,t,E,s,s,L,t,f,P,I,G))
  else:
    print("La estrategia de arbitraje es la siguiente: \n En t=0 días.\n 1. Suscribir un contrato futuro en {0} para {1} días.\n 2. Pedir prestado ${2} pesos al mismo plazo con interés de {3}%. \n 3. Cambiar los pesos prestados por 1 dólar en el mercado de contado. \n 4. Invertir 1 dólar  a una tasa de {4}%  al mismo plazo. \n \n En t= {5} días.\n 1. Recibir inversión de ${6} dólares. \n 2. Cambiar por ${7} pesos  usando el derivado.\n 3. Pagar el préstamo inicial por ${8} pesos.\n 4. Ganancia de ${9} pesos por dólar.".format(y,t,s,l,e,t,i,z,i2,g2))

#------------------------------------------------------------------------------
    
def ventana_1():
    raiz=Tk()
    raiz.title("FUTURO")
    raiz.geometry("5000x5000")
    #raiz.config(width=1000, height=1000)
    marco=Frame()
    #marco.config(bg="white",width="500", height="500")
    marco.pack()
    miimagen0=PhotoImage(file="commodities.png")
    labelimg=Label(marco, image=miimagen0).pack()
    variableLabel=Label(marco,text="""Un contrato futuro es un instrumento financiero en el cual se estipula la entrega de un activo en \n
un tiempo determinado a cierto precio. El activo a negociar puede ser trigo, soya, petróleo, oro, \n 
divisas o cualquier cosa en la cual el precio fluctúa, la finalidad de los futuros es eliminar la \n 
incertidumbre de los precios en fechas posteriores para compradores y vendedores.\n 
El activo a transar se denomina subyacente, el precio del futuro depende del precio del \n 
subyacente en el mercado de contado o mercado spot, el día en que se estipule él acuerdo. \n 
Como el precio del instrumento viene dado por el precio de otro activo, a los futuros se les \n
denominan derivados.\n
""").pack()

    def siguiente():
        raiz.destroy()
        ventana_2()
    Boton=Button(raiz , text="Siguiente", command=siguiente)
    Boton.pack()
    raiz.mainloop()

#------------------------------------------------------------------------------

def ventana_2():
    raiz2=Tk()
    raiz2.title("FUTURO")
    raiz2.geometry("5000x5000")
    #raiz2.config(width=1000, height=1000)
    marco=Frame()
    marco.config(bg="white",width="500", height="500")
    marco.pack()
    #miimagen0=PhotoImage(file="commodities.png")
    #labelimg=Label(marco, image=miimagen0).pack()
    variableLabel=Label(marco, text="""Un ejemplo para explicar el funcionamiento del derivado es una negociación con trigo. En un \n
caso hipotético, el precio del trigo para el día de hoy es de $3000 y este viene dado por oferta y demanda.\n
Tanto productores como compradores de trigo tienen incertidumbre del precio para \n el día de mañana, en una semana, un mes, etc.\n
Un productor puede pactar un precio de venta para su cosecha que estará lista en dos meses y \n 
una vez que encuentre una contraparte se puede constituir un contrato futuro.\n
Si en dos meses el precio del trigo en el mercado de contado es de $3200, el comprador en el \n 
contrato futuro ganó $200 y el productor pierde $200. Si por el contrario el trigo estuviese a \n
$2800  el productor es quien gana $200 y el comprador pierde $200.\n
Imaginemos que el precio es de $3200, dadas esas condiciones las partes tienen dos opciones \n para cerrar el acuerdo.\n
Pueden intercambiar trigo a $3000 directamente entre ellos.\n
Quien pierde, el productor, le da a su contraparte $200 y cada uno hace transacciones en el mercado de contado.\n
Sin importar que opción escojan, lo que acordaron en el contrato futuro se va hacer efectivo, \n 
alguien va a ganar y alguien va a perder la diferencia entre el precio acordado en el futuro y  el \n 
precio el dia que cierra la negociación en el mercado spot. Sin embargo, las dos partes \n 
eliminaron la incertidumbre del precio del activo en el futuro.\n
Cómo alguien siempre compra más caro o vende más barato, se tienen incentivos a no cumplir \n 
el acuerdo y hacer la negociación en el mercado de contado, una vez llegada la fecha final del \n
contrato futuro.\n
""").pack()    
    def siguiente():
        raiz2.destroy()
        ventana_3()
    Boton=Button(raiz2 , text="Siguiente", command=siguiente)
    Boton.pack()
    def anterior():
        raiz2.destroy()
        ventana_1()    
    Boton2=Button(raiz2 , text="Atras", command= anterior)
    Boton2.pack()
    raiz2.mainloop()    
    
#------------------------------------------------------------------------------
        
def ventana_3():
    raiz17=Tk()
    raiz17.title("Tutorial")
    raiz17.geometry("5000x5000")
    marco17=Frame()
    marco17.pack()
    def siguiente():
        raiz17.destroy()
        ventana_4()
    Boton=Button(raiz17 , text="Siguiente", command=siguiente)
    Boton.pack()
    def anterior():
        raiz17.destroy()
        ventana_2()    
    Boton2=Button(raiz17 , text="Atras", command= anterior)
    Boton2.pack()
    variableLabel17=Label(marco17, text=""" Para eliminar el riesgo de incumplimiento por alguna de las partes se creó la Cámara de \n
Compensación, esta entidad actúa como intermediaria entre compradores y vendedores. \n 
Retomando el ejemplo anterior, el productor hace un acuerdo con la cámara para vender el \n 
trigo  a $3000 y el comprador hace el mismo acuerdo anterior pero con la cámara.\n
La cámara es quien le responde a todos los participantes del mercado por el cumplimiento de los acuerdos.\n
Ademas, para evitar que las partes le incumplan a la cámara se exige que quien quiera\n 
hacer una negociación abra una cuenta a nombre de esta entidad.\n
La finalidad de la cuenta es para que las partes entreguen garantías como acciones o dinero, \n
para cubrir las pérdidas o depositar allí las ganancias obtenidas. En nuestro ejemplo si el precio \n 
pactado fue de $3000 y ahora es de $3200 ocurriría lo siguiente:\n
Pueden intercambiar trigo a $3000 directamente entre ellos.\n
A quien pierde, el productor, le son descontados $200 de su cuenta y quien gana, el comprador,\n
le son consignados $200  y cada uno hace transacciones en el mercado de\n contado.\n
Con la existencia de la cámara no sólo quienes están interesados en transar productos pueden\n 
negociar con futuros, especuladores y otros agentes del mercado pueden utilizarlos para generar ganancias.\n 
Gracias a esta congregación de agentes el mercado tiene liquidez y se puede \n 
garantizar que siempre existe una contraparte. Además gracias a la intermediación se pueden\n  
cerrar las operaciones antes del vencimiento.\n
Los futuros se negocian en bolsas de valores o mercantiles alrededor del mundo, en todas existe\n
una entidad como la cámara que garantiza el cumplimiento de las operaciones.\n
Para el caso de colombia Existe la Bolsa de Valores de Colombia (BVC) y la Cámara de Riesgo\n
Central de Contraparte de Colombia.\n
""" ).pack()
    raiz17.mainloop()

#------------------------------------------------------------------------------        

def ventana_4():
    raiz18=Tk()
    raiz18.title("Grafica")
    raiz18.geometry("8000x8000")
    marco18=Frame(raiz18)
    marco18.pack()
    miimagen=PhotoImage(file="Superpuesta.png")
    variableLabel18=Label(marco18, image=miimagen).pack()
    def siguiente():
        raiz18.destroy()
        ventana_5()
    Boton=Button(raiz18 , text="Siguiente", command=siguiente)
    Boton.pack()
    def anterior():
        raiz18.destroy()
        ventana_3()    
    Boton2=Button(raiz18 , text="Atras", command= anterior)
    Boton2.pack()
    variableLabel18=Label(marco18, text=""" En colombia se pueden hacer operaciones con futuros de sobre el índice Colcap, acciones, tasa \n 
de cambio COP/USD, títulos de Deuda Pública (TES) e inflación (IPC). A continuación \n
explicaremos como funciona una estrategia de arbitraje con divisas, en finanzas arbitraje es \n
negociar un activo entre dos mercados aprovechando las diferencias de precio para generar ganancias. \n
En un arbitraje no se necesita capital inicial, se solicita un préstamo para la negociación y cuando\n 
se cierran las posiciones se devuelve el dinero. Cómo se trata de un arbitraje con divisas se tiene\n 
que pedir prestado en una moneda e invertir en la otra. \n
En colombia quienes negocian con futuros de TRM son exportadores e importadores, pero los\n
especuladores tienen una gran participación en este mercado y al intentar aprovechar las\n 
diferencias de precios ocasionan que los precios entre el mercado de futuros y el mercado spot\n
tengan las mismas tendencias.\n
""" ).pack()
    raiz18.mainloop()
    
#------------------------------------------------------------------------------

def ventana_5():
    raiz19=Tk()
    raiz19.title("Grafica")
    raiz19.geometry("8000x8000")
    marco19=Frame(raiz19)
    marco19.pack()
    miimagen=PhotoImage(file="precio.png")
    variableLabel19=Label(marco19, image=miimagen).pack()
    def siguiente(tx):
        raiz19.destroy()
        ventana_6()
    Boton=Button(raiz19 , text="Siguiente", command=siguiente)
    Boton.pack()
    def anterior():
        raiz19.destroy()
        ventana_4()    
    Boton2=Button(raiz19 , text="Atras", command= anterior)
    Boton2.pack()
    variableLabel19=Label(marco19, text=""" Antes de poder realizar arbitraje es necesario definir el precio de el futuro sobre TRM, este\n 
depende de:\n
S es el valor del Dólar en el mercado de contado.\n
L es la tasa local  tasa en pesos\n 
E es la tasa en Dólares de Estados Unidos\n 
T es el periodo hasta el vencimiento del futuro (Dias/360)\n 
""").pack()
    raiz19.mainloop()  

#------------------------------------------------------------------------------
    
def ventana_6():
    raiz19=Tk()
    raiz19.title("Grafica")
    raiz19.geometry("8000x8000")
    marco19=Frame(raiz19)
    marco19.pack()   
    def siguiente():
        raiz19.destroy()
        ventana_7()
    Boton=Button(raiz19 , text="Siguiente", command=siguiente)
    Boton.pack()
    def anterior():
        raiz19.destroy()
        ventana_5()    
    Boton2=Button(raiz19 , text="Atras", command= anterior)
    Boton2.pack()    
    variableLabel19=Label(marco19, text="""La estrategia de arbitraje va a depender del valor de las tasas y la TRM del día en que se suscribe el contrato. \n
     Vamos a suponer que las tasas de inversión y préstamo son las mismas, teniendo una tasa en dólares del 4% y una \n
     tasa en pesos del 9%, la TRM se va a ubicar en $3293 y la fecha de vencimiento va a ser en 45 días.\n
     Esto da porresultado que el precio justo para un contrato futuro es de $3313.64. \n
     Sin embargo, los precios de los futuros dependen de la oferta y demanda en su mercado respectivo, \n
     la estrategia de arbitraje depende de si el precio de los futuros es mayor o menor a nuestro precio calculado.\n
     Si el precio del mercado de futuros es menor al nuestro, por ejemplo $3280 la estrategia de arbitraje es la siguiente:\n
     """).pack()
    raiz19.mainloop() 
    
#------------------------------------------------------------------------------
    
def ventana_7():
    raiz19=Tk()
    raiz19.title("Grafica")
    raiz19.geometry("8000x8000")
    marco19=Frame(raiz19)
    marco19.pack()   
    def siguiente():
        raiz19.destroy()
        ventana_8()
    Boton=Button(raiz19 , text="Siguiente", command=siguiente)
    Boton.pack()
    def anterior():
        raiz19.destroy()
        ventana_6()    
    Boton2=Button(raiz19 , text="Atras", command= anterior)
    Boton2.pack()    
    variableLabel19=Label(marco19, text="""En t=0 días.\n
1. Suscribir un contrato futuro en $3280 para 45 días. \n
2. Pedir prestado 1 dólar al mismo plazo con interés de 4%. \n
3. Cambiar el dólar prestado por $3293  en el mercado de contado. \n
4. Invertir los $3293 a una tasa de 9%  al mismo plazo. \n
\n
En t= 45 días.\n
1. Recibir inversión de $3328 . \n
2. Cambiar a $1.01463 dólares  usando el derivado.\n
3. Pagar el préstamo inicial por 1.0049146 dólares.\n
4. Ganancia de 0.0097153 dólares.\n
""").pack()
    raiz19.mainloop() 
    
#------------------------------------------------------------------------------
    
def ventana_8():
    raiz19=Tk()
    raiz19.title("Grafica")
    raiz19.geometry("8000x8000")
    marco19=Frame(raiz19)
    marco19.pack()   
    def siguiente():
        raiz19.destroy()
        ventana_9()
    Boton=Button(raiz19 , text="Siguiente", command=siguiente)
    Boton.pack()
    def anterior():
        raiz19.destroy()
        ventana_7()    
    Boton2=Button(raiz19 , text="Atras", command= anterior)
    Boton2.pack()    
    variableLabel19=Label(marco19, text="""Si el precio del mercado de futuros es mayor al nuestro, por ejemplo $3400 la estrategia de arbitraje es la siguiente: \n
En t=0 días.\n
1. Suscribir un contrato futuro en $3400 para 45 días.\n
2. Pedir prestado $3293 pesos al mismo plazo con interés de 9%. \n
3. Cambiar los pesos prestados por 1 dólar en el mercado de contado. \n
4. Invertir 1 dólar  a una tasa de 4%  al mismo plazo. \n
\n
1. En t= 45 días.\n
2. Recibir inversión de $1.00491 dólares. \n
3. Cambiar por $3416 pesos  usando el derivado.\n
4. Pagar el préstamo inicial por $3328 pesos.\n
5. Ganancia de $87. 335 pesos por dólar.\n
""").pack()
    raiz19.mainloop() 
    
#------------------------------------------------------------------------------
def ventana_9():
    raiz19=Tk()
    raiz19.title("Grafica")
    raiz19.geometry("8000x8000")
    marco19=Frame(raiz19)
    marco19.pack()

    pantalla1=Entry(marco19)
    pantalla1.grid(row=0, column=1)
                   
    pantalla2=Entry(marco19)
    pantalla2.grid(row=1, column=1)
    
    pantalla3=Entry(marco19)
    pantalla3.grid(row=2, column=1)
    
    pantalla4=Entry(marco19)
    pantalla4.grid(row=3, column=1)
    
    pantalla5=Entry(marco19)
    pantalla5.grid(row=4, column=1)
    
    
    Label1=Label(marco19, text="Subyacente (Tasa de cambio COP-DOLAR): ")
    Label1.grid(row=0, column=0)
    
    Label2=Label(marco19, text="Tasa Local (En porcentaje): ")
    Label2.grid(row=1, column=0)
    
    Label3=Label(marco19, text="Tasa Extrajera (En porcentaje): ")
    Label3.grid(row=2, column=0)
    
    Label4=Label(marco19, text="Vencimiento (Dias): ")
    Label4.grid(row=3, column=0)
    
    Label5=Label(marco19, text="Precio Futuro (En pesos por dólar): ")
    Label5.grid(row=4, column=0)
    
    def tasa(l,e):
      v=((l)-(e))
      return v
    
    def valor(r,t):
      w=math.exp((r/100)*(t/360))
      return w
    
    def precio(s,l,e,t):
      z=s*valor(tasa(l,e),t)
      return z
    
    def ejecutar(s,l,e,t,y):
      x=precio(s,l,e,t)
      f=s*valor(l,t)
      p=f/y
      i=1*valor(e,t)
      i2=s*valor(l,t)
      g=p-i
      z=y*i
      g2=z-i2
      if (y<x):
        a=("La estrategia de arbitraje es la siguiente:\n En t=0 días.\n 1. Suscribir un contrato futuro en {0} para {1} días. \n 2. Pedir prestado 1 dólar al mismo plazo con interés de {2} %. \n 3. Cambiar el dólar prestado por ${3}  en el mercado de contado. \n 4. Invertir los ${4} a una tasa de {5} %  al mismo plazo. \n \n En t= {6} días.\n 1. Recibir inversión de ${7} . \n 2. Cambiar a ${8} dólares  usando el derivado.\n 3. Pagar el préstamo inicial por ${9} dólares.\n 4. La ganancia es {10} dólares.".format(y,t,e,s,s,l,t,f,p,i,g))
      else:
        a=("La estrategia de arbitraje es la siguiente: \n En t=0 días.\n 1. Suscribir un contrato futuro en {0} para {1} días.\n 2. Pedir prestado ${2} pesos al mismo plazo con interés de {3}%. \n 3. Cambiar los pesos prestados por 1 dólar en el mercado de contado. \n 4. Invertir 1 dólar  a una tasa de {4}%  al mismo plazo. \n \n En t= {5} días.\n 1. Recibir inversión de ${6} dólares. \n 2. Cambiar por ${7} pesos  usando el derivado.\n 3. Pagar el préstamo inicial por ${8} pesos.\n 4. Ganancia de ${9} pesos por dólar.".format(y,t,s,l,e,t,i,z,i2,g2))
      return a  
    def fields():
        z=ejecutar(float(pantalla1.get()),float(pantalla2.get()),float(pantalla3.get()),float(pantalla4.get()),float(pantalla5.get()))
        ventana_10(z)  
    Boton0=Button(raiz19,text="Calcular",command=fields)
    Boton0.pack()    

    def anterior():
        raiz19.destroy()
        ventana_8()    
    Boton2=Button(raiz19 , text="Atras", command= anterior)
    Boton2.pack()
    raiz19.mainloop() 

#------------------------------------------------------------------------------

def ventana_10(tx):
    raiz19=Tk()
    raiz19.title("Grafica")
    raiz19.geometry("8000x8000")
    marco19=Frame(raiz19)
    marco19.pack()   
    def siguiente():
        raiz19.destroy()
    Boton=Button(raiz19 , text="Cerrar", command=siguiente)
    Boton.pack()
    def anterior():
        raiz19.destroy()
        ventana_9()    
    Boton2=Button(raiz19 , text="Atras", command= anterior)
    Boton2.pack()    
    variableLabel19=Label(marco19, text=tx).pack()
    raiz19.mainloop()

#------------------------------------------------------------------------------

    
    
ventana_1()
